### ISSUE TITLE
Explain that .bundle should be added to linked_dirs

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/bundler#96]
As explained in #95, the `bundle check` behavior used by this gem depends on `.bundle/config` from previous deployments. If this directory is not linked, `bundle check` will be ineffective and a slower `bundle install` will be used. This unnecessarily slows down deployments.

We should add this explanation to the README.

**Comment by mattbrictson** [comment]
Closed via #102

**Comment by allaire** [comment]
@mattbrictson Quick question, I don't have .bundle in my linked_dirs. I'm using capistrano-rails and it's not in the README (but `vendor/bundle` is). AFAIK, `bundle check` is still working correctly, even though `.bundle` is not linked, is it because `vendor/bundle` is? Should I also add `.bundle` to be safe?

Let me know and I will update the README of capistrano-rails if that's the case!

**Comment by mattbrictson** [comment]
@allaire Yes, I agree this should also be added to the capistrano-rails README. If you'd be willing to open a PR, that would be much appreciated!

As discussed in #95, `bundle check` doesn't accept the `--without` option, so unless `.bundle/config` is already present, it will check whether *all* of the Gemfile dependencies are satisfied, not just the production ones. So I am pretty sure linking `.bundle` it is necessary for `check` to work as intended.

**Comment by allaire** [comment]
@mattbrictson Great, gonna add it quick to the README :)
